name: Voidkeepinv
version: '${project.version}'
main: com.rk_dude02.keepinv
api-version: 1.19
description: A plugin that allows players to keep their inventory if they die from the void!
author: RK_Dude02
